### ISSUE TITLE
 bind EADDRINUSE 0.0.0.0:56700

### ISSUE THREAD

**Issue by jmcc94** [futomi/node-lifx-lan#38] opened 2021-04-21 03:26 UTC
Trying to run the following;

// Create a LifxLan object
const Lifx=require('node-lifx-lan')

Lifx.discover().then((device_list) => {
  device_list.forEach((device) => {
    console.log([
      device['ip'],
      device['mac'],
      device['deviceInfo']['label']
    ].join(' | '));
  });
}).catch((error) => {
  console.error(error);
});

and keep getting - Error: bind EADDRINUSE 0.0.0.0:56700

Any help appreciated

**Comment by alexweininger** [comment] 2021-06-18 00:15
Encountering the same error. I have no idea if it's related but I recently updated Windows. Here is my version:

``` 
Edition	Windows 10 Pro
Version	20H2
Installed on	‎2/‎27/‎2021
OS build	19042.1052
Experience	Windows Feature Experience Pack 120.2212.2020.0
```

I keep getting

```
Error: bind EACCES 0.0.0.0:56700
```

each time I try to discover. 

Also my Wifi went out and came back yesterday so I think that could be the problem.

**Comment by ghost** [comment] 2021-07-03 01:48
I'm also seeing this problem (on the same build of Windows, if that's related).

```
Error: bind EADDRINUSE 0.0.0.0:56700
    at dgram.js:357:20
    at processTicksAndRejections (internal/process/task_queues.js:83:21) {
  errno: -4091,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 56700
}
```

Using `netstat -a -p UDP` I can confirm the port is closed correctly when I terminate my application. When I run it again, I get the above error when the `discover()` call is made. If comment out that call, I do not get the error.

Edit: I ran into this again today, and this time it was happening 100%. Again, netstat reported no applications on UDP 56700. I had a look at the library source, and it appears to be doing nothing more than dgram createSocket & bind. I tried using the "reuseAddr" option on createSocket, but it made no difference. I then closed everything down and ran a node app that did nothing other than create/bind the socket, and it failed just the same. I was able to bind other ports without any problems. I then rebooted my machine and upon restart I was able to bind 56700 without problem. I suspect this has nothing to do with the node-lifx-lan library, and more likely just windows handling closing ports badly.

**Comment by dresende** [comment] 2022-01-11 20:49
Looking at the code, the resolution is simple. The problem is that `.init()` initializes an UDP socket if not initialized yet, but this process takes a few milliseconds out of event loop, so if you call `createDevice` more than once in a row it will throw.

You need to start using module like:

```js
const Lifx = require("node-lifx-lan");

Lifx.init().then(() => {
    // now you can discover, create devices, etc..
})
```

**Comment by ghost** [comment] 2022-01-11 22:13
Thanks @dresende, but OP is already calling discover().then (which internally calls init().then) and I'm calling await Lifx.init() before using the library at all. I'm pretty sure this is unrelated to the Lifx library, but rather Windows socket handling.

**Comment by dresende** [comment] 2022-01-11 22:18
> Thanks @dresende, but OP is already calling discover().then (which internally calls init().then)

But if I call .createDevice twice in the same event, init() will not finish and be called twice, trying to bind the UDP socket twice.

> I'm pretty sure this is unrelated to the Lifx library, but rather Windows socket handling.

You're wrong. I'm on macOS and had the same problem, that's why I came here. And I solved it by doing just that.

**Comment by ghost** [comment] 2022-01-11 22:42
If you don't wait for init() to complete before calling createDevice multiple times, then you will absolutely run into this error. However, I always wait for init() to complete before calling any other library function, and I'm saying that the issue I was seeing appeared to be Windows specific.

**Closed as completed** 2022-04-23 10:21 UTC
